#ifndef SUCCESS_CODE_DEFINITIONS_H
#define SUCCESS_CODE_DEFINITIONS_H

// General Success Codes
#define SUCCESS 0
#define SUCESS_ADDED_NEW_NODE 10
#define SUCCESS_ADDED_TO_PENDING_LIST 11
#define SUCESS_ADDED_NEW_NODE_RESZING_TRIGGERED 20



#endif // SUCCESS_CODE_DEFINITIONS_H