#ifndef SUCCESS_CODE_DEFINITIONS_H
#define SUCCESS_CODE_DEFINITIONS_H

// General Success Codes
#define SUCCESS 0
#define SUCESS_ADDED_NEW_NODE 10
#define SUCCESS_ADDED_TO_PENDING_LIST 11
#define SUCESS_ADDED_NEW_NODE_RESZING_TRIGGERED 20

// Specific Success Codes for Sub-Hash-Bucket Operations
#define BLOOM_FILTER_DISABLED 30
#define BLOOM_FILTER_CHECK_KEY_MAY_EXIST 31
#define BLOOM_FILTER_CHECK_KEY_NOT_EXIST 32



#endif // SUCCESS_CODE_DEFINITIONS_H