# ============================================================================
# Generate Coverage Report
# ============================================================================
# This script processes .gcda files generated by test runs and produces
# .gcov files for coverage analysis.
#
# Usage: cmake -P GenerateCoverage.cmake

# Check if gcov is available
find_program(GCOV_EXECUTABLE gcov)
if(NOT GCOV_EXECUTABLE)
    message(FATAL_ERROR "gcov not found")
endif()

message(STATUS "Generating coverage reports...")

if(NOT DEFINED COVERAGE_BINARY_DIR OR COVERAGE_BINARY_DIR STREQUAL "")
    message(FATAL_ERROR "COVERAGE_BINARY_DIR is required")
endif()

if(NOT DEFINED COVERAGE_OUTPUT_DIRECTORY OR COVERAGE_OUTPUT_DIRECTORY STREQUAL "")
    set(COVERAGE_OUTPUT_DIRECTORY "${COVERAGE_BINARY_DIR}/coverage")
endif()
file(MAKE_DIRECTORY "${COVERAGE_OUTPUT_DIRECTORY}")

message(STATUS "Coverage output directory: ${COVERAGE_OUTPUT_DIRECTORY}")

# Find all object files and generate gcov data
file(GLOB_RECURSE GCDA_FILES "${COVERAGE_BINARY_DIR}/*.gcda")
if(NOT GCDA_FILES)
    message(FATAL_ERROR "No .gcda coverage files found in ${COVERAGE_BINARY_DIR}")
endif()

list(LENGTH GCDA_FILES GCDA_COUNT)
message(STATUS "Found ${GCDA_COUNT} .gcda files")

# Process each gcda file with gcov
foreach(GCDA_FILE ${GCDA_FILES})
    get_filename_component(GCDA_DIR "${GCDA_FILE}" DIRECTORY)
    message(STATUS "Processing: ${GCDA_FILE}")
    execute_process(
        COMMAND ${GCOV_EXECUTABLE} -o ${GCDA_DIR} "${GCDA_FILE}"
        WORKING_DIRECTORY ${COVERAGE_OUTPUT_DIRECTORY}
        RESULT_VARIABLE GCOV_RESULT
    )
    if(NOT GCOV_RESULT EQUAL 0)
        message(FATAL_ERROR "gcov failed for ${GCDA_FILE}")
    endif()
endforeach()

# Count generated gcov files
file(GLOB GCOV_FILES "${COVERAGE_OUTPUT_DIRECTORY}/*.gcov")
list(LENGTH GCOV_FILES GCOV_COUNT)
if(GCOV_COUNT EQUAL 0)
    message(FATAL_ERROR "gcov did not generate any report files")
endif()
message(STATUS "Generated ${GCOV_COUNT} .gcov files in ${COVERAGE_OUTPUT_DIRECTORY}")

message(STATUS "Coverage report generation complete")
